### ISSUE TITLE
Malformed HTTP status code

### ISSUE THREAD

**Issue by clinique** [angelbarrera92/tlwpa4220#7]
Hello.
Thanks for your work.

I tried to use your code with my TL-WPA4220 (HW rev TL-WPA4220 5.0, FW : 1.0.12 Build 230309 Rel.64136n (6985)) without success.

Here's the command line test result : 

```
sysadmin@morpheus:~/tpa4220/tlwpa4220-main$ ./tlwpa4220 cli --device-ip="192.168.0.197" --password="xxxxx" wireless-statistics
2023/07/26 11:33:23 Running command wireless-statistics
2023/07/26 11:33:23 Error getting wireless statistics: Post "http://192.168.0.197/admin/wireless?form=statistics": net/http: HTTP/1.x transport connection broken: malformed HTTP status code "192.168.0.197\x00\x00User-Agent\x00"
2023/07/26 11:33:23 Post "http://192.168.0.197/admin/wireless?form=statistics": net/http: HTTP/1.x transport connection broken: malformed HTTP status code "192.168.0.197\x00\x00User-Agent\x00"

```

**Comment by negmos** [comment]
Same issue over here.. i guess the WebPage format was changed

**Comment by angelbarrera92** [comment]
Ill have to take a look to my devices, i guess im outdated as it works at home :)

**Comment by angelbarrera92** [comment]
Im checking mine,
![Captura desde 2024-01-13 11-32-12](https://github.com/angelbarrera92/tlwpa4220/assets/14357604/2a492072-b47b-420e-a32d-6f86208bed77)

And im in the latest firmware version available.
I guess your PLC is newer than mine and, probably, you have a different firmware version. Isn't it?
Could you paste an screenshot like mine?
